title: 狗熊岭乐园
description: 熊出没主题小站，记录狗熊岭的欢乐日常
baseurl: ""
url: "https://lyq-bx.github.io"

author: 站长
theme_color: "#3a7d44"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag