<<<<<<< HEAD
title: 熊出没森林
baseurl: ""
url: "https://lyq-bx.github.io"
=======
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
>>>>>>> 1e689541bde161e38749989735df735ee89c362a
